# Generated by Django 6.0.6 on 2026-06-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('year_established', models.CharField(max_length=10)),
                ('website', models.URLField(blank=True, null=True)),
                ('company_type', models.CharField(max_length=50)),
                ('primary_market', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_designation', models.CharField(max_length=100)),
                ('contact_mobile', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pin', models.CharField(blank=True, max_length=20, null=True)),
                ('top_destinations', models.CharField(max_length=255)),
                ('avg_monthly_bookings', models.CharField(max_length=100)),
                ('client_types', models.JSONField(default=list)),
                ('expected_monthly_room_nights', models.CharField(max_length=100)),
                ('preferred_room_category', models.CharField(blank=True, max_length=100, null=True)),
                ('commission_requested', models.CharField(max_length=50)),
                ('preferred_payment_terms', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('docs_gst', models.BooleanField(default=False)),
                ('docs_pan', models.BooleanField(default=False)),
                ('docs_company', models.BooleanField(default=False)),
                ('docs_cheque', models.BooleanField(default=False)),
                ('agreed', models.BooleanField(default=False)),
                ('signatory_name', models.CharField(max_length=255)),
                ('signatory_designation', models.CharField(max_length=100)),
                ('signatory_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('vendor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_approval', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
