# Generated by Django 5.2.1 on 2026-06-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_bg_color',
            field=models.CharField(blank=True, default='#0f2418', help_text='Header background color (e.g. #0f2418 or any CSS color)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
