# Generated by Django 5.2.1 on 2026-06-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_make_signatory_date_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='docs_cheque',
            field=models.FileField(blank=True, null=True, upload_to='agent_docs/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='docs_company',
            field=models.FileField(blank=True, null=True, upload_to='agent_docs/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='docs_gst',
            field=models.FileField(blank=True, null=True, upload_to='agent_docs/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='docs_pan',
            field=models.FileField(blank=True, null=True, upload_to='agent_docs/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
